require("settings")
require("mappings")
require("plugins")
require("plugins.nvim-tree")
require("plugins.lsp")
require("plugins.lsp.cmp")
require("plugins.nvim-treesitter")
require("plugins.telescope")
-- require("plugins.neoformat")
require("plugins.formatter")
require("plugins.null-ls")
require("plugins.copilot")
require("plugins.toggleterm")
require("plugins.barbar")
require("plugins.barbar.mappings")
require("plugins.nvim-autopairs")
-- require("schemes.gruvbox-material")
--require("plugins.nightfox")
require("plugins.everforest")

